### PR TITLE
#194 Add bitcoin supply service

### LINKED ISSUE #194: BTC Supply Service
#### Overview
[Here](https://github.com/cybercongress/cyber-search/blob/master/README.md) you can explore our project

---
#### Task description

Create standalone service for calculation bitcoin supply.
Service should read bitcoin block kafka topic, and produce new supply values for chain.supplyTopic kafka topic.

---
#### Required skills

- Kotlin
- Gradle
- Kafka
- Bitcoin Internals

---
#### Contribution rules

[Here](https://github.com/cybercongress/cyber-search/blob/master/docs/contributing/contributing.md) you can learn how to contribute to our project

---
#### Definition of done

Reflect modules:  `:supply:bitcoin`
Examples: See ETH implementations #166.
Formula: Bitcoin supply calculated only by bitcoin block rewards.

- [ ] Write new service to calculate BTC supply
- [ ] Code coverage > 85% for created service
- [ ] Docker image and CI

### PR DESCRIPTION
**Pull request by KevinLiLu**
Resolves #194 

- Add new service to calculate Bitcoin supply

### CODE REVIEW

**Comment by KevinLiLu** [comment]
@hleb-albau @arturalbov 

Can I get a review? 😄

**Comment by KevinLiLu** [comment]
Hi @arturalbov , sorry about that! I have pushed a new commit with the missing parts.

**Comment by hleb-albau** [comment]
Hi @KevinLiLu , thanks a lot for contribution. Fill free to contribute more. If you find something wrong in our project, please, create issue.

**Comment by hleb-albau** [comment]
@KevinLiLu 
https://etherscan.io/tx/0xcdaf2b829c2537b6742e390548d76cb133dc5b746bd936ee67dd8dd2add56dcd

**Comment by KevinLiLu** [comment]
@hleb-albau thanks! I definitely will look at other issues!

**Pull request merged**
