### PR TITLE
Improve BitcoinBlock getBlockReward

### PR DESCRIPTION
**Pull request by KevinLiLu**
- Use formula to calculate bitcoin block reward given block number

### CODE REVIEW

**Comment by KevinLiLu** [comment]
@arturalbov @hleb-albau 

Can someone review this? Can you also re-run the test? The `:common-kafka:test` works on my local...

**Comment by arturalbov** [comment]
Hi @KevinLiLu
@hleb-albau will review your request soon
Thanks for contributing :)

**Comment by hleb-albau** [comment]
Hi @KevinLiLu. Thanks for PR, I will send you some tips on gitcoin.
Also, if you have a time,please, have a look at issues #185 and #255.

**Comment by KevinLiLu** [comment]
Thanks @hleb-albau! I’m working on #185 right now 😃

**Comment by hleb-albau** [comment]
@KevinLiLu Did you manage to get you tip?

**Comment by KevinLiLu** [comment]
@hleb-albau I upgraded my MetaMask and there was some issue with the new version and receiving tips on GitCoin so I am getting it sorted out with the GitCoin team currently.

**Pull request merged**
