### PR TITLE
#20 Open Source Features

### PR DESCRIPTION
**Pull request by hleb-albau**
@arturalbov @asadovka Please, leave comments.

### CODE REVIEW

**Comment by hleb-albau** [comment]
@asadovka will clarify some issues after discussing browser integration.

**Comment by 21xhipster** [comment]
@hleb-albau can you change project status to alpha?

**Comment by 21xhipster** [comment]
@hleb-albau Please add 21xhipster to cybernode organization on Docker hub

**Comment by 21xhipster** [comment]
http://api.cybersearch.io/search?query=42 - Fantastic!

**Comment by hleb-albau** [comment]
@21xhipster added to dockerhub
@21xhipster status was changed

**Pull request merged**
