### PR TITLE
Add cyberSearch landing prototype

### PR DESCRIPTION
**Pull request by SaveTheAles**
#232 

prototype available in `cyberSearchPrototype.sketch` file at the repo root

@arturalbov  @hleb-albau 

Screenshot for you

image

### CODE REVIEW

**Comment by SaveTheAles** [comment]
@arturalbov I propose you to discuss it with @hleb-albau @xhipster  and @litvintech

**Comment by arturalbov** [comment]
Charts section will be discussed and implemented in #239

**Comment by hleb-albau** [comment]
One more -> Yet another
Easy to add ->  Easy to index 
Useful  -> Extendable

For Users section should contain:
api, api docs, monitoring sections

**Comment by cyberadmin** [comment]
@hleb-albau looks better?

image

**Comment by SaveTheAles** [comment]
here we go @hleb-albau 
image

**Comment by SaveTheAles** [comment]
@arturalbov @hleb-albau @Olga584  Also I propose animated logo

**Comment by arturalbov** [comment]
@SaveTheAles It would be great!

**Comment by SaveTheAles** [comment]
@xhipster 

Stats section in discussion state now. Which stats we need to show is discussing [here](https://github.com/cybercongress/cyber-search/issues/239). For now we leaving this section empty till discussion ends. 

image

**Pull request merged**
